In [3]:
%matplotlib inline

In [4]:
import torch
import numpy as np

In [5]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
x_rand

tensor([[0.4901, 0.1819],
        [0.5537, 0.7547]])

In [10]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")

First row: tensor([1., 1., 1., 1.])


In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
y1 = tensor @ tensor.T
y1

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [15]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [16]:
y3 = torch.rand_like(y1)
y3

tensor([[0.3419, 0.2550, 0.9211, 0.3907],
        [0.8797, 0.0191, 0.5936, 0.8761],
        [0.2716, 0.7388, 0.0442, 0.8882],
        [0.1346, 0.1020, 0.7978, 0.8696]])

In [17]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [19]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])